pipeline:
  build:
    image: java:openjdk-8
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew publish -PmavenUser=${maven_user} -PmavenPass=${maven_pass} -PmavenURL=sftp://108.61.192.172:22/var/www/maven2/ -S -i
