pages:
  - Home: 'index.md'
  - Getting Started:
    - Home: 'gettingstarted/index.md'

site_name: Mist Core Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - toc:
      permalink: ' '

theme: null
theme_dir: 'mist_theme'
